- name: Create Folder
  ansible.builtin.template:
    src: job1.xml
    dest: /tmp/job1.xml

- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/job1.xml') }}"
    name: "{{item}}"
    url: http://172.31.4.172:8080
    user: admin
    password: "{{jenkins_password}}"
  loop:
    - frontend
    - cart
    - catalogue

