- name: Create Folder
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
#    url: http://172.31.4.172:8080
    url: http://172.31.11.11:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Multi branch pipeline jobs
  ansible.builtin.include_tasks: mbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Single pipeline jobs
  ansible.builtin.include_tasks: sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"