- name: Check if job exists or not
  community.general.jenkins_job_info:
    url: http://172.31.4.172:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}"
  register: out
  ignore_errors: yes

- name: Create Config file
  ansible.builtin.template:
    src: m-job.xml
    dest: /tmp/m-job.xml
  vars:
    unique_key: lookup('community.general.random_string', special=false, upper=false, length=12)

- name: Create job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/m-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.4.172:8080
    user: admin
    password: "{{jenkins_password}}"